### ISSUE TITLE
Question about slackWebKey

### ISSUE THREAD

**Issue by patricklunney** [paypal/rallyslack#1]
Hi - what is the slackWebKey? Can't find it in Slack APIs.

**Comment by Xerxous** [comment]
The `slackWebKey` can be generated [here](https://api.slack.com/web). This token is used to look up Slack ID codes with names in the slack group via the account that generated the token. This allows the [rallybot](https://github.com/paypal/rallyslack) to write the name in the slack group when writing logs about who modified a Rally object(User Story, Defect, etc) in its comment section.

**Comment by dhruvmishra** [comment]
Marking this issue as closed as it looks resolved in Feb 2017.
